### ISSUE TITLE
Unable to follow basic example

### ISSUE THREAD

**Issue by zshift** [fabianboesiger/debug-plotter#2]
Using vscode with rust_analyzer, the macro doesn't appear to be recognizing the variables passed in.

There also appear to be typos in the docs, (missing `!` to designate the macro calls)

![image](https://user-images.githubusercontent.com/581760/140813891-8a64198e-8cb8-455f-9311-97c7df56fd0d.png)

There is no output, and no runtime errors when executed with `cargo run`

**Comment by zshift** [comment]
The root README has also not been updated to reflect the functionality in version 0.2.0.

**Comment by fabianboesiger** [comment]
I just updated the README, it should be:

```rust
fn main() {
    for a in 0usize..10usize {
        let b = (a as f32 / 2.0).sin() * 10.0;
        let c = 5 - (a as i32);

        debug_plotter::plot!(a, b, c where caption = "My Plot");
    }
}
```

I use rust-analyzer too, and on my end it works flawlessly. No idea what the problem could be.

**Comment by fabianboesiger** [comment]
@zshift are your issues resolved?
